#include <Servo.h>
#include <NewPing.h>

#define BUZZER 3
#define PIN_RODA_KIRI 4
#define PIN_RODA_KANAN 5
#define KIPAS 6

Servo SERVO_RODA_KIRI;
Servo SERVO_RODA_KANAN;
bool KONDISI_ROBOT;

#define PENGIRIM_SINYAL_KANAN 8
#define PENERIMA_SINYAL_KANAN 7
#define JARAK_MAKSIMUM_SENSOR_ULTRASONIK 100
NewPing SONAR_KANAN(PENERIMA_SINYAL_KANAN, PENGIRIM_SINYAL_KANAN, JARAK_MAKSIMUM_SENSOR_ULTRASONIK);

#define PENGIRIM_SINYAL_KIRI 10
#define PENERIMA_SINYAL_KIRI 9
#define JARAK_MAKSIMUM_SENSOR_ULTRASONIK 100
NewPing SONAR_KIRI(PENERIMA_SINYAL_KIRI, PENGIRIM_SINYAL_KIRI, JARAK_MAKSIMUM_SENSOR_ULTRASONIK);

#define PENGIRIM_SINYAL_DEPAN 12
#define PENERIMA_SINYAL_DEPAN 11
#define JARAK_MAKSIMUM_SENSOR_ULTRASONIK 100
NewPing SONAR_DEPAN(PENERIMA_SINYAL_DEPAN, PENGIRIM_SINYAL_DEPAN, JARAK_MAKSIMUM_SENSOR_ULTRASONIK);

int LAJU_RODA =320;
int NILAI_BELOK = 620; 
int NILAI_BERHENTI_KANAN  = 89; 
int NILAI_BERHENTI_KIRI   = 89; 
int Jarak_Min_Dinding    = 1;
int Jarak_Avr_Dinding    = 7; 
int Jarak_Max_Dinding    =15;
int Warna_Lintasan   = 500; 
int NILAI_API        = 500; 
